### ISSUE TITLE
optionally supporting with sexp?

### ISSUE THREAD

**Issue by ericbmerritt** [mjambon/atdgen#23]
It would be very convenient  if you could set an option on the atdgen command line that causes it to output the `with sexp` annotation for generated records. There are ways around this, and we use them, but this would be so much nicer for us and, theoretically, non-impactful for those folks not using core. You could probably even make it generic with a 'record annotations' flag or some such.

**Comment by ericbmerritt** [comment]
@mjambon should I close this or leave it open. I hate leaving an issue open that isn't going to be worked on.

**Comment by mjambon** [comment]
I'd rather leave it open. It's just that someone's got to do it.

**Comment by ericbmerritt** [comment]
no worries. maybe I can dig into it one of these days. I would rather send a pr rather than an issue any way.

**Comment by rgrinberg** [comment]
@mjambon If I wanted to tackle this, how would you recommend to go about this?

**Comment by mjambon** [comment]
Roughly, without looking at the code:
* add a command-line option
* pass the parameter around in some record (I don't remember how cleanly this is done in the current implementation)
* at the time of emitting the code (file `ag_oj_emit.ml` for json and optionally file `ag_ob_emit.ml` for biniou), print the type definitions with `with sexp`. Perhaps a more generic option would allow us to append an arbitrary string rather than always `with sexp`.

The difficulty may be that type definitions are not printed by atdgen itself but by the atd library. This needs to be checked. If that's the case, the module in charge of printing type definitions needs to take an option for adding `with sexp`, or anything else we might want to print after type definitions.

If don't know if anyone out there uses the atd library for some tool I'm not aware of (besides atdgen and atdj). Compatibility issues are probably minor.

The general contribution guidelines are here: https://github.com/mjambon/documents/blob/master/how-to-contribute.md

**Comment by mjambon** [comment]
I just had a look at the code. It turns out the formatting of OCaml type definitions is done within atdgen, in file `ag_ocaml.ml`. That should be straightforward to modify because it is private and we don't have to worry about compatibility or about exposing a perfect interface.

Formatting is done using easy-format. It consist in building a tree with some embedded options defining formatting rules. In this case, you probably want to create a `Label` node, so you can achieve this structure:

```
type t = {
  ...
}
  with sexp
```

where the node representing the type definition is the "label", i.e. the first argument of the `Label` constructor, and the string `"with sep"` is wrapped in an `Atom` and constitutes the second argument of the `Label` constructor. Looking at examples should help.

**Comment by rgrinberg** [comment]
@mjambon I believe you can close this.
