### ISSUE TITLE
Failure when trying to wrap float values

### ISSUE THREAD

**Issue by toots** [mjambon/atdgen#61]
It looks like the parsing/generating layer still injects float-related functions when trying to abstract values using `wrap`/`unwrap`:

```
type rounded_float = float wrap
  <ocaml t="float"
         wrap="float_of_string"
         unwrap="Printf.sprintf \"%.02f\"">
```

```
% ocamlfind ocamlc -linkpkg -package atdgen -c rounded_j.ml
File "rounded_j.ml", line 10, characters 9-10:
Error: This expression has type string but an expression was expected of type
         float
zsh: exit 2     ocamlfind ocamlc -linkpkg -package atdgen -c rounded_j.ml
```

Indeed:
```
let write__1 = (
  fun ob x -> (
    let x = ( Printf.sprintf "%.02f" ) x in (
      Yojson.Safe.write_float
    ) ob x)
)
```

**Comment by mjambon** [comment]
If you want the json representation to be a string and the ocaml representation to be a float, the type definition should be:
```ocaml
type rounded_float = string wrap (* <-- string here *)
  <ocaml t="float"
         wrap="float_of_string"
         unwrap="Printf.sprintf \"%.02f\"">
```
If you want the reverse, i.e. the OCaml definition to be a string and the json representation to be a number, then you have to change the `<ocaml ...>` annotation accordingly.

**Comment by toots** [comment]
I would like both to be `float` but also to be able to round up to 2 decimal when exporting to JSON. I though module/wrap-unwrap was simply a layer to define your own custom serialization, did I get this wrong?

**Comment by mjambon** [comment]
`wrap` allows you to wrap the original data in the atd type (`t` in `t wrap`) in an OCaml type of your choosing that may not make sense in other languages that use the type definitions. In Java for example, using `atdj`, the `<ocaml ...>` annotation is ignored and a plain `double` would be used.

Here you kind of want to use in reverse, since the json representation is special, not the OCaml representation. There's no wrap function for json (which would have to be written in javascript I guess or some language that all atd processors understand), and since I assume you're only using this between OCaml and json, you'd just do what you were trying to do, using `float wrap <ocaml  ...>`.

A naive adaptation of your code is the following:
```ocaml
type rounded_float = float wrap
  <ocaml t="float"
         wrap="fun x -> x"
         unwrap="fun x -> float_of_string (Printf.sprintf \"%.02f\" x)">
```

A lower-level approach that I don't recommend is to define an `abstract` atd type and implement the function that writes to the json buffer directly. This lets you write arbitrary data and it won't check that you're writing valid json. You can use this to extend the json syntax, with the risk of creating malformed data. The atd syntax is:
```ocaml
type rounded_float <ocaml from="Rounded_json_float"> = abstract
```
and you would need to implement at least the modules `Rounded_json_float_t` and `Rounded_json_float_j` with the proper signature (type `t`, functions `write_t` and `read_t`).

**Comment by toots** [comment]
Works great, thanks for clearing that up!
