### ISSUE TITLE
JSON array with multiple types

### ISSUE THREAD

**Issue by andrenth** [mjambon/atdgen#74]
Hi

Is there an idiomatic way to represent JSON arrays that may contain items of different types? Currently I'm using a record with fields from both types, all optional, and then checking at runtime for the `Some` ones, which feels less than optimal...

Thanks!

**Comment by mjambon** [comment]
It's possible but there's no solution simple enough that I can write an example without looking up existing code or documentation. So the situation isn't good but it's doable.

If the items are all json objects and they have a string field that indicates what type they have such as `"type": "apple"`, this is solved nicely with the `tag_field` feature. Check out https://mjambon.github.io/atdgen-doc/atdgen#field-tag_field.

Otherwise, a more generic but hackish and difficult approach is to:

1. read the items as a json AST.
2. wrap them using the `wrap` feature, which allows you to provide an arbitrary function that will "sniff" the json AST and decide what OCaml type it should have and then call a function to convert the json AST to the desired OCaml representation. You may end up converting the json AST back to a json string so you can use atdgen-generated *_of_string functions.

There may be examples here and there for the second approach but hopefully you don't need it.

**Comment by andrenth** [comment]
Hi

Sorry for taking so long to reply. I had abandoned my project but now I'm giving it another look. I'm working with the JSON schema for [Swagger 2.0](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md), which has some objects with fields that can be of two types. 

For exemple, the "Path item" object has a "parameters" field, which is a list of either "Parameter" objects or "Reference" objects. There's no field that identifies the type of an object, but only References have a "$ref" field, so I thought I could use that to make a decision, but looking at the atdgen docs it's unclear to me how to do that.

**Comment by mjambon** [comment]
I'm not sure if that's what inpired you to resume your efforts, but I just posted a [related answer on the OCaml forum earlier today](https://discuss.ocaml.org/t/json-validation/1671/5?u=mjambon).

I think you can adapt that code to get what you want. The general idea is that you'd inspect the json tree before deciding which OCaml type it complies with, possibly transform it to make its structure compatible with ATD/OCaml types, and then use the function generated by atdgen to turn the json blob into a clean OCaml value.

Let me know if there are extra difficulties that I missed.

**Comment by andrenth** [comment]
I hadn't seen that. I'll take a look, thanks!

**Comment by andrenth** [comment]
I got it to work by declaring the record field as `json` and then inspecting it manually to convert it into the appropriate time. Thanks!
